# Generated by Django 4.2 on 2023-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(),
        ),
    ]
