# Generated by Django 4.2 on 2023-05-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_email', '0002_alter_email_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(max_length=5000),
        ),
    ]
