# Generated by Django 4.2 on 2023-06-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_email', '0003_product_alter_email_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
